language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t kewynakshlley/rd -f Dockerfile.dev .
script:
    - docker run -e CI=true kewynakshlley/rd npm run test
    
